    post:
      responses:
        "201":
          description: The queued source file details
          content:
            application/json:
              schema:
                $ref: "../schemas/ingest/responses/queuedsourceresponse.yaml#/QueuedSourceResponse"
        "400":
          description: A list of validation and other errors
          content:
            application/json:
              schema:
                $ref: "../schemas/ingest/responses/ingesterrorresponse.yaml#/IngestErrorResponse"
      description: |
        Queue a source file to be fetched from a URL and stored by Shotstack. Source files can be videos, images, audio
        files and fonts. Once ingested, new [output renditions](#tocs_outputs) can be created from the source file.

        **Base URL:** <a href="#">https://api.shotstack.io/ingest/{version}</a>
      summary: Fetch Source
      operationId: postSource
      requestBody:
        description: >-
          Ingest a video, image, audio or font file from the provided URL. Optionally provide a list of output
          renditions.
        content:
          application/json:
            example:
              $ref: "../definitions/source.yaml"
            schema:
              $ref: "../schemas/ingest/source.yaml#/Source"
        required: true
      security:
        - DeveloperKey: []
      tags:
        - Ingest

    get:
      description: |
        Retrieve a list of ingested source files stored against a users account and stage.

        **Base URL:** <a href="#">https://api.shotstack.io/ingest/{version}</a>
      summary: List Sources
      operationId: getSources
      responses:
        "200":
          description: The list of ingested source files stored against a users account
          content:
            application/json:
              schema:
                $ref: "../schemas/ingest/responses/sourcelistresponse.yaml#/SourceListResponse"
      security:
        - DeveloperKey: []
      tags:
        - Ingest